runtime: python37
env: flex

runtime_config:
  python_version: 3

handlers:
-url: static
  static_dir:static

-kind: User
properties:
- name: username
direction: asc

#[START gae_flex_storage_yaml]
env_variables:
    CLOUD_STORAGE_BUCKET: memes-marketplace.appspot.com
#[END gae_flex_storage_yaml]

