runtime: python37

handlers:
-url: static
  static_dir: static

- kind: User
  properties:
  - name: username
    direction: asc
  - name: bio
  - name: friends
  - name: memes
  - name: picture
    
    
